version: '3.9'

services:
  web:
    build: .
    container_name: smartcart-web
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8080
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    environment:
      - PORT=8080